[package]
name = "all-pairs-hamming"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.15" # MIT or Apache-2.0
anyhow = "=1.0.62"    # MIT or Apache-2.0
