[package]
name = "find-simdoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hamming-join = { path = "../hamming-join" }  # MIT or Apache-2.0
lsh = { path = "../lsh" }  # MIT or Apache-2.0

clap = { version = "~3.2.1", features = ["derive"] }  # MIT or Apache-2.0
fasthash = "0.4.0"
hashbrown = "0.12.3"
